var upper = 1000000000;
var randomNumber = getRandomNumber(upper);
var guess;
var counter = 0;

// Used for showing comma separated numbers, i.e., thousands, millions, billions.
function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}

// This is the random number generator
function getRandomNumber(upper) {
  return Math.floor( Math.random() * upper ) + 1;
}

// Prints out the result of random number generator
document.write("The random number generated by computer is " + numberWithCommas(randomNumber) + ".</p>");

// This stores the start time of the while loop
var timeStart = performance.now();
// This calls the getRandomNumber function to generate random numbers until it finds a match with the original random number
while (guess !== randomNumber) {
  guess = getRandomNumber(upper);
  counter++;
}
// This stores the stop time of the while loop
var timeEnded = performance.now();

// Prints out the results
document.write("<p>The correct random number guessed by the script is " + numberWithCommas(guess) + ".</p>");
document.write("<p>It took " + numberWithCommas(counter) + " tries to arrive at the correct guess.");
document.write("<p>It took the script " + ((timeEnded - timeStart)/1000).toFixed(2) + " seconds to guess correctly.</p>");