var upper = 1000000000;
var randomNumber = getRandomNumber(upper);
var guess;
var counter = 0;

function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}

function getRandomNumber(upper) {
  return Math.floor( Math.random() * upper ) + 1;
}

document.write("The random number generated by computer is " + numberWithCommas(randomNumber) + ".</p>");

var timeStart = performance.now();
while (guess !== randomNumber) {
  guess = getRandomNumber(upper);
  counter++;
}
var timeEnded = performance.now();

document.write("<p>The correct random number guessed by the script is " + numberWithCommas(guess) + ".</p>");
document.write("<p>It took " + numberWithCommas(counter) + " tries to arrive at the correct guess.");
document.write("<p>It took the script " + ((timeEnded - timeStart)/1000).toFixed(2) + " seconds to guess correctly.</p>");